version: '3.7'
services:
 jenkins:
  container_name: jenkins-pipeline
  env_file:
    - .env
  build : ./jenkins
  ports:
    - '0.0.0.0:9090:8080' 
  volumes:
    - ./jenkins-repo:/opt/repo
    - ./jenkins-data:/var/jenkins_home
    - ./jenkins-docker-certs:/certs/client
  user: "1000:1000"